<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMB4XS2f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMB4XS2f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMB4XS2f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMB4XS2f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMB4XS2f\App_KernelDevDebugContainer([
    'container.build_hash' => 'MB4XS2f',
    'container.build_id' => '107b1320',
    'container.build_time' => 1775224010,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMB4XS2f');
