when@dev:
    _errors:
<<<<<<< HEAD
        resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
=======
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
>>>>>>> origin/integrationv11
        prefix: /_error
