package com.esprit.services.ai;

import com.esprit.entities.Reclamation;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;

public class OpenAiCompatibleSmartReplyGenerator implements SmartReplyGenerator {

    private static final ObjectMapper MAPPER = new ObjectMapper();
    private static final String KNOWLEDGE = """
            Reclamation support assistant rules:
            - Be concise, polite, and practical.
            - Never promise refunds/compensation unless admin confirms.
            - Ask for missing evidence when needed (order id, date, screenshots).
            - If legal threat, fraud, police, court, or abuse appears, mark requires_human_review=true.
            - Reply in the user's language when obvious (English/French).
            """;

    private final ReclamationAutoReplyConfig config;
    private final HttpClient client;

    public OpenAiCompatibleSmartReplyGenerator(ReclamationAutoReplyConfig config) {
        this.config = config;
        this.client = HttpClient.newBuilder()
                .connectTimeout(Duration.ofSeconds(20))
                .build();
    }

    @Override
    public SmartReplyGeneration generate(Reclamation reclamation) {
        if (reclamation == null) {
            return fallback("INVALID", "Missing reclamation.");
        }
        try {
            String requestBody = buildRequestBody(reclamation);
            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(config.getApiUrl()))
                    .timeout(Duration.ofSeconds(45))
                    .header("Authorization", "Bearer " + config.getApiKey())
                    .header("Content-Type", "application/json")
                    .POST(HttpRequest.BodyPublishers.ofString(requestBody, StandardCharsets.UTF_8))
                    .build();

            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));
            if (response.statusCode() < 200 || response.statusCode() >= 300) {
                return fallback("API_ERROR", "AI provider returned HTTP " + response.statusCode());
            }

            String content = extractAssistantContent(response.body());
            if (content == null || content.isBlank()) {
                return fallback("PARSE_ERROR", "AI response did not contain content.");
            }

            JsonNode root = MAPPER.readTree(content);
            String message = text(root.path("response"), "Thank you for your message. An admin will review your case.");
            String intent = text(root.path("intent"), "GENERAL");
            double confidence = doubleValue(root.path("confidence"), 0.55);
            boolean requiresHuman = booleanValue(root.path("requires_human_review"), true);
            String reason = text(root.path("reason"), "Generated by AI model.");

            return new SmartReplyGeneration(message, intent, confidence, requiresHuman, reason);
        } catch (Exception e) {
            return fallback("EXCEPTION", "AI generation failed: " + e.getMessage());
        }
    }

    private String buildRequestBody(Reclamation reclamation) throws IOException {
        String userText = "Sujet: " + safe(reclamation.getSujet()) + "\nDescription: " + safe(reclamation.getDescription());
        String systemPrompt = """
                You are a reclamation-response assistant for customer support.
                Output strict JSON only, with keys:
                intent, response, confidence, requires_human_review, reason.
                confidence must be a number between 0 and 1.
                """ + "\n" + KNOWLEDGE;

        JsonNode payload = MAPPER.createObjectNode()
                .put("model", config.getModel())
                .put("temperature", 0.2)
                .set("messages", MAPPER.createArrayNode()
                        .add(MAPPER.createObjectNode()
                                .put("role", "system")
                                .put("content", systemPrompt))
                        .add(MAPPER.createObjectNode()
                                .put("role", "user")
                                .put("content", userText)));

        return MAPPER.writeValueAsString(payload);
    }

    private String extractAssistantContent(String rawBody) throws IOException {
        JsonNode root = MAPPER.readTree(rawBody);
        JsonNode choices = root.path("choices");
        if (!choices.isArray() || choices.isEmpty()) {
            return null;
        }
        JsonNode message = choices.get(0).path("message");
        return text(message.path("content"), null);
    }

    private String text(JsonNode node, String defaultValue) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return defaultValue;
        }
        String value = node.asText();
        return value == null || value.isBlank() ? defaultValue : value.trim();
    }

    private double doubleValue(JsonNode node, double defaultValue) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return defaultValue;
        }
        double value = node.asDouble(defaultValue);
        if (value < 0.0 || value > 1.0) {
            return defaultValue;
        }
        return value;
    }

    private boolean booleanValue(JsonNode node, boolean defaultValue) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return defaultValue;
        }
        return node.asBoolean(defaultValue);
    }

    private SmartReplyGeneration fallback(String intent, String reason) {
        return new SmartReplyGeneration(
                "Thank you for your message. Your case has been escalated to an admin for a detailed review.",
                intent,
                0.5,
                true,
                reason
        );
    }

    private String safe(String value) {
        return value == null ? "" : value.trim();
    }
}
