<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0VRyltfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0VRyltf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'socialFeedViewBuilder' => ['privates', 'App\\Service\\SocialFeedViewBuilder', 'getSocialFeedViewBuilderService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'socialFeedViewBuilder' => 'App\\Service\\SocialFeedViewBuilder',
            'security' => '?',
        ]);

        if (isset($container->privates['.service_locator.0VRyltf'])) {
            return $container->privates['.service_locator.0VRyltf'];
        }

        return $container->privates['.service_locator.0VRyltf'] = $instance;
    }
}
