<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCrudAutocompleteTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'EasyCorp\Bundle\EasyAdminBundle\Form\Type\CrudAutocompleteType' shared service.
     *
     * @return \EasyCorp\Bundle\EasyAdminBundle\Form\Type\CrudAutocompleteType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'DataMapperInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'easycorp'.\DIRECTORY_SEPARATOR.'easyadmin-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Type'.\DIRECTORY_SEPARATOR.'CrudAutocompleteType.php';

        $a = ($container->privates['twig'] ?? $container->load('getTwigService'));

        if (isset($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'])) {
            return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'];
        }

        $instance = new \EasyCorp\Bundle\EasyAdminBundle\Form\Type\CrudAutocompleteType($a);

        if (isset($container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'])) {
            return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'];
        }

        return $container->privates['EasyCorp\\Bundle\\EasyAdminBundle\\Form\\Type\\CrudAutocompleteType'] = $instance;
    }
}
