<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k8V37WF.App\Controller\CommentController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k8V37WF.App\\Controller\\CommentController::delete()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator.k8V37WF.App\\Entity\\Comment', NULL, 'Cannot autowire service ".service_locator.k8V37WF": it needs an instance of "App\\Entity\\Comment" but this type has been excluded because it\'s a Doctrine entity.'],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'comment' => 'App\\Entity\\Comment',
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\CommentController::delete()', $container);
    }
}
