<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentControllercreateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w7FAFTO.App\Controller\CommentController::create()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.w7FAFTO.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.w7FAFTO": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.'],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'notificationManager' => ['privates', 'App\\Service\\SocialNotificationManager', 'getSocialNotificationManagerService', true],
        ], [
            'post' => 'App\\Entity\\Post',
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'entityManager' => '?',
            'security' => '?',
            'notificationManager' => 'App\\Service\\SocialNotificationManager',
        ]))->withContext('App\\Controller\\CommentController::create()', $container);

        if (isset($container->privates['.service_locator.w7FAFTO.App\\Controller\\CommentController::create()'])) {
            return $container->privates['.service_locator.w7FAFTO.App\\Controller\\CommentController::create()'];
        }

        return $container->privates['.service_locator.w7FAFTO.App\\Controller\\CommentController::create()'] = $instance;
    }
}
