<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendRequestControllerdeclineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q0Rw4X_.App\Controller\FriendRequestController::decline()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q0Rw4X_.App\\Controller\\FriendRequestController::decline()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'friendRequest' => ['privates', '.errored..service_locator.q0Rw4X_.App\\Entity\\FriendRequest', NULL, 'Cannot autowire service ".service_locator.q0Rw4X_": it needs an instance of "App\\Entity\\FriendRequest" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'friendRequest' => 'App\\Entity\\FriendRequest',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\FriendRequestController::decline()', $container);
    }
}
