<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendRequestControllersendService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mVZFE71.App\Controller\FriendRequestController::send()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mVZFE71.App\\Controller\\FriendRequestController::send()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'friendRequestRepository' => ['privates', 'App\\Repository\\FriendRequestRepository', 'getFriendRequestRepositoryService', true],
            'friendshipRepository' => ['privates', 'App\\Repository\\FriendshipRepository', 'getFriendshipRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'userRepository' => 'App\\Repository\\UserRepository',
            'friendRequestRepository' => 'App\\Repository\\FriendRequestRepository',
            'friendshipRepository' => 'App\\Repository\\FriendshipRepository',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\FriendRequestController::send()', $container);
    }
}
