<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeedControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0VRyltf.App\Controller\FeedController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.0VRyltf'] ?? $container->load('get_ServiceLocator_0VRyltfService'));

        if (isset($container->privates['.service_locator.0VRyltf.App\\Controller\\FeedController::index()'])) {
            return $container->privates['.service_locator.0VRyltf.App\\Controller\\FeedController::index()'];
        }

        $instance = $a->withContext('App\\Controller\\FeedController::index()', $container);

        if (isset($container->privates['.service_locator.0VRyltf.App\\Controller\\FeedController::index()'])) {
            return $container->privates['.service_locator.0VRyltf.App\\Controller\\FeedController::index()'];
        }

        return $container->privates['.service_locator.0VRyltf.App\\Controller\\FeedController::index()'] = $instance;
    }
}
