<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendRequestControlleracceptService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e3CqLu3.App\Controller\FriendRequestController::accept()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e3CqLu3.App\\Controller\\FriendRequestController::accept()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'friendRequest' => ['privates', '.errored..service_locator.e3CqLu3.App\\Entity\\FriendRequest', NULL, 'Cannot autowire service ".service_locator.e3CqLu3": it needs an instance of "App\\Entity\\FriendRequest" but this type has been excluded because it\'s a Doctrine entity.'],
            'friendshipRepository' => ['privates', 'App\\Repository\\FriendshipRepository', 'getFriendshipRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'friendRequest' => 'App\\Entity\\FriendRequest',
            'friendshipRepository' => 'App\\Repository\\FriendshipRepository',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\FriendRequestController::accept()', $container);
    }
}
