<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFriendRequestService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.e3CqLu3.App\Entity\FriendRequest' shared service.
     *
     * @return \App\Entity\FriendRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.e3CqLu3": it needs an instance of "App\\Entity\\FriendRequest" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
