<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ZOgOdO.App\Controller\PostController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ZOgOdO.App\\Controller\\PostController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'socialPostMediaUploader' => ['privates', 'App\\Service\\SocialPostMediaUploader', 'getSocialPostMediaUploaderService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'entityManager' => '?',
            'socialPostMediaUploader' => 'App\\Service\\SocialPostMediaUploader',
            'security' => '?',
        ]))->withContext('App\\Controller\\PostController::new()', $container);
    }
}
