<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4ufTv7e.App\Controller\PostController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4ufTv7e.App\\Controller\\PostController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'postRepository' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'commentRepository' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'friendshipRepository' => ['privates', 'App\\Repository\\FriendshipRepository', 'getFriendshipRepositoryService', true],
            'socialFeedViewBuilder' => ['privates', 'App\\Service\\SocialFeedViewBuilder', 'getSocialFeedViewBuilderService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'postRepository' => 'App\\Repository\\PostRepository',
            'commentRepository' => 'App\\Repository\\CommentRepository',
            'friendshipRepository' => 'App\\Repository\\FriendshipRepository',
            'socialFeedViewBuilder' => 'App\\Service\\SocialFeedViewBuilder',
            'security' => '?',
        ]))->withContext('App\\Controller\\PostController::show()', $container);
    }
}
