<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfileControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wt2lBgW.App\Controller\ProfileController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wt2lBgW.App\\Controller\\ProfileController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'profileImageUploader' => ['privates', 'App\\Service\\ProfileImageUploader', 'getProfileImageUploaderService', true],
        ], [
            'entityManager' => '?',
            'profileImageUploader' => 'App\\Service\\ProfileImageUploader',
        ]))->withContext('App\\Controller\\ProfileController::edit()', $container);
    }
}
