<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jUnuWqC.App\Controller\PostController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jUnuWqC.App\\Controller\\PostController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.jUnuWqC.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.jUnuWqC": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'socialPostMediaUploader' => ['privates', 'App\\Service\\SocialPostMediaUploader', 'getSocialPostMediaUploaderService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'post' => 'App\\Entity\\Post',
            'entityManager' => '?',
            'socialPostMediaUploader' => 'App\\Service\\SocialPostMediaUploader',
            'security' => '?',
        ]))->withContext('App\\Controller\\PostController::edit()', $container);
    }
}
