<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPostReportControllerreportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._UnM2bi.App\Controller\PostReportController::report()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._UnM2bi.App\\Controller\\PostReportController::report()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator._UnM2bi.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator._UnM2bi": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.'],
            'postReportRepository' => ['privates', 'App\\Repository\\PostReportRepository', 'getPostReportRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'post' => 'App\\Entity\\Post',
            'postReportRepository' => 'App\\Repository\\PostReportRepository',
            'entityManager' => '?',
            'security' => '?',
        ]))->withContext('App\\Controller\\PostReportController::report()', $container);
    }
}
