<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerverifyUserEmailService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0g9ezNl.App\Controller\RegistrationController::verifyUserEmail()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailVerifier' => ['privates', 'App\\Service\\EmailVerifier', 'getEmailVerifierService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'emailVerifier' => 'App\\Service\\EmailVerifier',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::verifyUserEmail()', $container);

        if (isset($container->privates['.service_locator.0g9ezNl.App\\Controller\\RegistrationController::verifyUserEmail()'])) {
            return $container->privates['.service_locator.0g9ezNl.App\\Controller\\RegistrationController::verifyUserEmail()'];
        }

        return $container->privates['.service_locator.0g9ezNl.App\\Controller\\RegistrationController::verifyUserEmail()'] = $instance;
    }
}
