<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReactionControllertoggleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.be01MnJ.App\Controller\ReactionController::toggle()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.be01MnJ.App\\Controller\\ReactionController::toggle()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'post' => ['privates', '.errored..service_locator.be01MnJ.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.be01MnJ": it needs an instance of "App\\Entity\\Post" but this type has been excluded because it\'s a Doctrine entity.'],
            'postReactionRepository' => ['privates', 'App\\Repository\\PostReactionRepository', 'getPostReactionRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
            'notificationManager' => ['privates', 'App\\Service\\SocialNotificationManager', 'getSocialNotificationManagerService', true],
        ], [
            'post' => 'App\\Entity\\Post',
            'postReactionRepository' => 'App\\Repository\\PostReactionRepository',
            'entityManager' => '?',
            'security' => '?',
            'notificationManager' => 'App\\Service\\SocialNotificationManager',
        ]))->withContext('App\\Controller\\ReactionController::toggle()', $container);
    }
}
