<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialFeedViewBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SocialFeedViewBuilder' shared autowired service.
     *
     * @return \App\Service\SocialFeedViewBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SocialFeedViewBuilder.php';

        $a = ($container->privates['App\\Service\\SocialMediaResolver'] ?? $container->load('getSocialMediaResolverService'));

        if (isset($container->privates['App\\Service\\SocialFeedViewBuilder'])) {
            return $container->privates['App\\Service\\SocialFeedViewBuilder'];
        }

        $instance = new \App\Service\SocialFeedViewBuilder(($container->privates['App\\Repository\\PostRepository'] ?? $container->load('getPostRepositoryService')), ($container->privates['App\\Repository\\CommentRepository'] ?? $container->load('getCommentRepositoryService')), ($container->privates['App\\Repository\\FriendRequestRepository'] ?? $container->load('getFriendRequestRepositoryService')), ($container->privates['App\\Repository\\FriendshipRepository'] ?? $container->load('getFriendshipRepositoryService')), ($container->privates['App\\Repository\\NotificationRepository'] ?? $container->load('getNotificationRepositoryService')), ($container->privates['App\\Repository\\PostReactionRepository'] ?? $container->load('getPostReactionRepositoryService')), ($container->privates['App\\Repository\\PostReportRepository'] ?? $container->load('getPostReportRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), $a);

        if (isset($container->privates['App\\Service\\SocialFeedViewBuilder'])) {
            return $container->privates['App\\Service\\SocialFeedViewBuilder'];
        }

        return $container->privates['App\\Service\\SocialFeedViewBuilder'] = $instance;
    }
}
