<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialMediaControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y6wZvs5.App\Controller\SocialMediaController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'socialMediaResolver' => ['privates', 'App\\Service\\SocialMediaResolver', 'getSocialMediaResolverService', true],
        ], [
            'socialMediaResolver' => 'App\\Service\\SocialMediaResolver',
        ]))->withContext('App\\Controller\\SocialMediaController::show()', $container);

        if (isset($container->privates['.service_locator.y6wZvs5.App\\Controller\\SocialMediaController::show()'])) {
            return $container->privates['.service_locator.y6wZvs5.App\\Controller\\SocialMediaController::show()'];
        }

        return $container->privates['.service_locator.y6wZvs5.App\\Controller\\SocialMediaController::show()'] = $instance;
    }
}
