<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSocialMediaResolverService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SocialMediaResolver' shared autowired service.
     *
     * @return \App\Service\SocialMediaResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SocialMediaResolver.php';

        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->privates['App\\Service\\SocialMediaResolver'])) {
            return $container->privates['App\\Service\\SocialMediaResolver'];
        }

        $instance = new \App\Service\SocialMediaResolver($a, ($container->services['kernel'] ?? $container->get('kernel', 1)), $container->getEnv('APP_SECRET'));

        if (isset($container->privates['App\\Service\\SocialMediaResolver'])) {
            return $container->privates['App\\Service\\SocialMediaResolver'];
        }

        return $container->privates['App\\Service\\SocialMediaResolver'] = $instance;
    }
}
