<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_Manager_ApiLoginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'security.authenticator.manager.api_login' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\AuthenticatorManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'AuthenticatorManagerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'UserAuthenticatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-http'.\DIRECTORY_SEPARATOR.'Authentication'.\DIRECTORY_SEPARATOR.'AuthenticatorManager.php';

        $a = ($container->privates['debug.security.authenticator.json_login.api_login'] ?? $container->load('getDebug_Security_Authenticator_JsonLogin_ApiLoginService'));

        if (isset($container->privates['security.authenticator.manager.api_login'])) {
            return $container->privates['security.authenticator.manager.api_login'];
        }

        $instance = new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([$a], ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['debug.security.event_dispatcher.api_login'] ?? $container->load('getDebug_Security_EventDispatcher_ApiLoginService')), 'api_login', ($container->privates['logger'] ?? self::getLoggerService($container)), true, \Symfony\Component\Security\Http\Authentication\ExposeSecurityLevel::None, []);

        if (isset($container->privates['security.authenticator.manager.api_login'])) {
            return $container->privates['security.authenticator.manager.api_login'];
        }

        return $container->privates['security.authenticator.manager.api_login'] = $instance;
    }
}
