<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDirectoryControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7iCkdby.App\Controller\UserDirectoryController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7iCkdby.App\\Controller\\UserDirectoryController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userDirectory' => ['privates', 'App\\Service\\UserDirectory', 'getUserDirectoryService', true],
        ], [
            'userDirectory' => 'App\\Service\\UserDirectory',
        ]))->withContext('App\\Controller\\UserDirectoryController::index()', $container);
    }
}
