<?php

namespace ContainerMB4XS2f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDirectoryControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UserDirectoryController' shared autowired service.
     *
     * @return \App\Controller\UserDirectoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'UserDirectoryController.php';

        $container->services['App\\Controller\\UserDirectoryController'] = $instance = new \App\Controller\UserDirectoryController();

        $instance->setContainer(($container->privates['.service_locator.BPfedfJ'] ?? $container->load('get_ServiceLocator_BPfedfJService'))->withContext('App\\Controller\\UserDirectoryController', $container));

        return $instance;
    }
}
